version: '3'

services:
  django:
    env_file: .env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 80:8000
      - 5678:5678
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_PORT=5432
    ports:
      - 5431:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  celery:
    env_file: .env
    command: celery -A django-backend worker
    build: .
    volumes:
      - .:/app

  celery-beat:
    env_file: .env
    build: .
    command: celery -A django-backend beat -l info
    volumes:
      - .:/app

  redis:
    image: redis:3.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data
      
volumes:
  redis:
    external: false
  postgres_data:

