# Generated by Django 3.1.7 on 2021-11-26 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIncomeDash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_for_service', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicedash', to='services.service', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Dashboard',
                'verbose_name_plural': 'Services Dashboards',
            },
        ),
        migrations.CreateModel(
            name='ProjectsIncomeDash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_collecetd_projects', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_remaining_projects', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectsdash', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Projects Dashboard',
                'verbose_name_plural': 'Projects Dashboards',
            },
        ),
        migrations.CreateModel(
            name='ExpenseIncomeDash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_for_category', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expense_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensecat', to='expenses.expensecategory', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ExpCategory Dashboard',
                'verbose_name_plural': 'ExpCategories Dashboards',
            },
        ),
        migrations.CreateModel(
            name='ExpenseDash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_exp_cat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_exp_cat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TotExpCategories Dashboard',
                'verbose_name_plural': 'TotExpCategories Dashboards',
            },
        ),
        migrations.CreateModel(
            name='CashFlowDash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CashFlow Dashboard',
                'verbose_name_plural': 'CashFlow Dashboards',
            },
        ),
    ]
