# Generated by Django 3.1.7 on 2021-12-07 16:19

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211130_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default-logo.jpg', null=True, upload_to=apps.authentication.models.ProfileImage_Upload),
        ),
    ]
