# Generated by Django 3.1.7 on 2021-12-07 17:46

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20211207_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/User/Images/default-logo.png', max_length=400, null=True, upload_to=apps.authentication.models.ProfileImage_Upload),
        ),
    ]
