# Generated by Django 3.1.7 on 2021-12-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20211209_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationkey',
            name='code',
        ),
    ]
