# Generated by Django 3.1.7 on 2021-12-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_verificationkey_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationkey',
            name='code',
            field=models.IntegerField(default=1234, max_length=4),
        ),
    ]
